name: "ðŸ—ï¸ Container Build"

on:
  pull_request:
    branches:
      - main
    paths:
      - container/**
  push:
    branches:
      - main
    paths:
      - container/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Install qemu dependency
        run: |-
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Get Uptime-Kuma Version
        run: |-
          VERSION=`sed -nr "s;.*docker.io/louislam/uptime-kuma:(.*)-debian.*;\1;p" container/Containerfile`
          echo "APP_VERSION=${VERSION}"
          echo "APP_VERSION=${VERSION}" >> $GITHUB_ENV

      - id: container
        name: Build Container Image
        uses: redhat-actions/buildah-build@b13805753a7ac93d18d14b22f6ebdf8499a3a95e # tag=v2.9
        with:
          image: uptime-kuma
          tags: >-
            latest
            ${{ env.APP_VERSION }}
          oci: true
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          containerfiles: |-
            container/Containerfile

      - name: Push container image to quay.io
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: redhat-actions/push-to-registry@f787883d70a3cc66d399816d0385ac4aec7079f9 # tag=v2.5
        with:
          image: ${{ steps.container.outputs.image }}
          tags: ${{ steps.container.outputs.tags }}
          registry: quay.io/k3rnel-pan1c
          username: ${{ secrets.QUAY_USR }}
          password: ${{ secrets.QUAY_PWD }}

      - name: Push container image to ghcr.io
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: redhat-actions/push-to-registry@f787883d70a3cc66d399816d0385ac4aec7079f9 # tag=v2.5
        with:
          image: ${{ steps.container.outputs.image }}
          tags: ${{ steps.container.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
